workflows:
  ios-release:
    name: IwanaProxy iOS
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.iwanian.iwanaproxy
    scripts:
      - name: Build iOS app
        script: |
          xcodebuild \
            -project "IwanaProxy.xcodeproj" \
            -scheme "IwanaProxy" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/IwanaProxy.xcarchive \
            archive
    artifacts:
      - build/IwanaProxy.xcarchive/**/*.ipa
      - build/IwanaProxy.xcarchive/**/*.app
      - /tmp/xcodebuild_logs/*.log
