workflows:
  ios-release:
    name: IwanaProxy iOS
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Build iOS app
        script: |
         xcodebuild \
          -project "IwanaProxy.xcodeproj" \
          -scheme "IwanaProxy" \
          -configuration Release \
          -sdk iphonesimulator \
          -destination 'generic/platform=iOS Simulator' \
          CODE_SIGNING_ALLOWED=NO \
          build
    artifacts:
      - build/IwanaProxy.xcarchive/**/*.ipa
      - build/IwanaProxy.xcarchive/**/*.app
      - /tmp/xcodebuild_logs/*.log
